-- Kiwi Supabase staging foundation.
--
-- This migration is intentionally additive and does not touch Cloudflare D1.
-- D1 remains the production source of truth until the shadow copy is verified
-- and a separate production cutover is explicitly approved.

begin;

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

-- Existing Kiwi identifiers and timestamps are preserved so the D1 export can
-- be imported without rewriting IDs or epoch-millisecond values.
create table public.accounts (
  id text primary key,
  email text not null unique,
  name text,
  business text,
  salt text not null,
  hash text not null,
  created_ts bigint not null,
  status text not null default 'active',
  contact_email text,
  billing_email text,
  constraint accounts_status_check check (status in ('active', 'suspended'))
);

create table public.account_users (
  auth_user_id uuid not null references auth.users(id) on delete cascade,
  account_id text not null references public.accounts(id) on delete cascade,
  role text not null default 'owner',
  created_at timestamptz not null default now(),
  primary key (auth_user_id, account_id),
  constraint account_users_role_check check (role in ('owner', 'manager', 'staff'))
);

create index account_users_account_idx on public.account_users (account_id);

create table public.operators (
  id text primary key,
  label text,
  salt text not null,
  hash text not null,
  created_ts bigint not null
);

create table public.merchant_config (
  merchant text primary key,
  features jsonb not null default '{}'::jsonb,
  plan text,
  type text,
  account_id text references public.accounts(id) on delete set null,
  name text,
  status text,
  city text,
  mrr bigint,
  updated_ts bigint not null,
  constraint merchant_status_check check (status is null or status in ('active', 'suspended'))
);

create index merchant_config_account_idx on public.merchant_config (account_id);

create table public.sales (
  id text primary key,
  merchant text not null,
  amount bigint not null,
  method text not null,
  label text,
  ref text,
  ts bigint not null,
  lines jsonb,
  void_ts bigint,
  void_reason text,
  void_note text,
  void_actor text,
  void_actor_id text
);

create index sales_merchant_idx on public.sales (merchant, ts);

create table public.staff_pins (
  id text primary key,
  merchant text not null,
  pin text not null,
  name text,
  role text not null,
  created_ts bigint not null,
  unique (merchant, pin)
);

create index staff_pins_merchant_idx on public.staff_pins (merchant);

create table public.pairings (
  id bigint generated by default as identity primary key,
  code text not null,
  merchant text not null,
  type text,
  subtype text,
  name text,
  account_id text,
  created_ts bigint not null,
  expires_ts bigint not null,
  used_ts bigint
);

create unique index pairings_code_live_idx on public.pairings (code) where used_ts is null;

create table public.pair_attempts (
  ip text primary key,
  fails integer not null default 0,
  first_ts bigint not null,
  blocked_until bigint
);

create table public.menus (
  merchant text primary key,
  name text,
  type text,
  data jsonb not null,
  updated_ts bigint not null
);

create table public.orders (
  id text primary key,
  merchant text not null,
  number integer not null,
  mode text not null,
  table_no text,
  total bigint not null,
  lines jsonb not null,
  status text not null,
  created_ts bigint not null,
  updated_ts bigint not null,
  session_id text,
  server_name text,
  menu_rev bigint,
  priced_ts bigint,
  client_ref text,
  paid_ts bigint,
  channel text,
  ext_ref text,
  customer jsonb
);

create index orders_merchant_idx on public.orders (merchant, updated_ts);
create index orders_session_idx on public.orders (session_id);
create unique index orders_client_ref_idx
  on public.orders (merchant, client_ref) where client_ref is not null;

create table public.channel_links (
  id text primary key,
  merchant text not null,
  channel text not null,
  label text,
  hash text not null,
  config jsonb,
  status text not null default 'active',
  created_ts bigint not null,
  last_ts bigint,
  last_err text,
  constraint channel_links_status_check check (status in ('active', 'paused'))
);

create index channel_links_merchant_idx on public.channel_links (merchant, channel);

create table public.catalogs (
  merchant text primary key,
  data jsonb not null,
  rev bigint not null,
  updated_ts bigint not null
);

create table public.store_docs (
  merchant text not null,
  feature text not null,
  data jsonb not null,
  rev bigint not null,
  updated_ts bigint not null,
  primary key (merchant, feature)
);

create table public.clients (
  merchant text not null,
  id text not null,
  name text not null default '',
  phone text not null default '',
  email text not null default '',
  birthday text not null default '',
  gender text not null default '',
  city text not null default '',
  address text not null default '',
  notes text not null default '',
  points bigint not null default 0,
  stamps bigint not null default 0,
  visits bigint not null default 0,
  spend bigint not null default 0,
  consent integer not null default 0,
  consent_email integer not null default 0,
  source text not null default 'caisse',
  first_seen bigint not null default 0,
  last_seen bigint not null default 0,
  updated_ts bigint not null default 0,
  srv_ts bigint not null default 0,
  deleted integer not null default 0,
  primary key (merchant, id),
  constraint clients_consent_check check (consent in (0, 1)),
  constraint clients_consent_email_check check (consent_email in (0, 1)),
  constraint clients_deleted_check check (deleted in (0, 1))
);

create index clients_sync_idx on public.clients (merchant, srv_ts);

create table public.config_audit (
  id bigint generated by default as identity primary key,
  merchant text not null,
  feature text not null,
  enabled integer not null,
  actor text not null default '',
  actor_id text not null default '',
  ts bigint not null,
  constraint config_audit_enabled_check check (enabled in (0, 1))
);

create index config_audit_merchant_idx on public.config_audit (merchant, ts);

create table public.sale_audit (
  id bigint generated by default as identity primary key,
  merchant text not null,
  sale_id text not null,
  action text not null,
  reason text not null default '',
  note text not null default '',
  actor text not null default '',
  actor_id text not null default '',
  amount bigint not null default 0,
  method text not null default '',
  ref text not null default '',
  sale_ts bigint not null default 0,
  impact jsonb,
  ts bigint not null,
  constraint sale_audit_action_check check (action in ('void', 'restore'))
);

create index sale_audit_merchant_idx on public.sale_audit (merchant, ts);
create index sale_audit_sale_idx on public.sale_audit (sale_id);

create table public.account_audit (
  id bigint generated by default as identity primary key,
  account_id text not null default '',
  merchant text not null default '',
  action text not null,
  prev text not null default '',
  next text not null default '',
  reason text not null default '',
  actor text not null default '',
  actor_id text not null default '',
  detail jsonb,
  ts bigint not null
);

create index account_audit_account_idx on public.account_audit (account_id, ts);
create index account_audit_merchant_idx on public.account_audit (merchant, ts);

create table public.reset_tokens (
  selector text primary key,
  account_id text not null,
  verifier text not null,
  created_ts bigint not null,
  expires_ts bigint not null,
  used_ts bigint,
  actor text not null default '',
  actor_id text not null default ''
);

create index reset_tokens_account_idx on public.reset_tokens (account_id, created_ts);

create table public.table_sessions (
  id text primary key,
  merchant text not null,
  mode text not null default 'table',
  table_no text not null default '',
  status text not null default 'open',
  closed_by text not null default '',
  opened_ts bigint not null,
  seen_ts bigint not null,
  closed_ts bigint,
  constraint table_sessions_mode_check check (mode in ('table', 'takeout')),
  constraint table_sessions_status_check check (status in ('open', 'closed'))
);

create unique index table_sessions_live_idx
  on public.table_sessions (merchant, table_no)
  where status = 'open' and mode = 'table';
create index table_sessions_seen_idx
  on public.table_sessions (merchant, status, seen_ts);

create table public.order_desk (
  merchant text primary key,
  seen_ts bigint not null
);

create table public.import_runs (
  id bigint generated always as identity primary key,
  source text not null,
  source_snapshot text not null,
  status text not null,
  row_counts jsonb not null default '{}'::jsonb,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  error text,
  constraint import_runs_status_check check (status in ('running', 'complete', 'failed'))
);

-- Explicit identity values imported from D1 do not advance PostgreSQL identity
-- sequences. The importer calls this once after all batches are verified.
create or replace function public.finalize_d1_import()
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  max_id bigint;
begin
  select coalesce(max(id), 0) into max_id from public.pairings;
  perform setval(pg_get_serial_sequence('public.pairings', 'id'), greatest(max_id, 1), max_id > 0);

  select coalesce(max(id), 0) into max_id from public.config_audit;
  perform setval(pg_get_serial_sequence('public.config_audit', 'id'), greatest(max_id, 1), max_id > 0);

  select coalesce(max(id), 0) into max_id from public.sale_audit;
  perform setval(pg_get_serial_sequence('public.sale_audit', 'id'), greatest(max_id, 1), max_id > 0);

  select coalesce(max(id), 0) into max_id from public.account_audit;
  perform setval(pg_get_serial_sequence('public.account_audit', 'id'), greatest(max_id, 1), max_id > 0);
end;
$$;

revoke all on function public.finalize_d1_import() from public, anon, authenticated;
grant execute on function public.finalize_d1_import() to service_role;

-- Supabase Auth maps to the existing Kiwi account model through account_users.
-- SECURITY DEFINER is deliberate: policies can check the mapping without
-- granting direct access to another user's membership rows.
create or replace function private.owns_account(target_account text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.account_users au
    where au.auth_user_id = auth.uid()
      and au.account_id = target_account
  );
$$;

create or replace function private.owns_merchant(target_merchant text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.merchant_config mc
    join public.account_users au on au.account_id = mc.account_id
    where mc.merchant = target_merchant
      and au.auth_user_id = auth.uid()
  );
$$;

revoke all on function private.owns_account(text) from public;
revoke all on function private.owns_merchant(text) from public;
grant execute on function private.owns_account(text) to authenticated, service_role;
grant execute on function private.owns_merchant(text) to authenticated, service_role;

-- Every public table has RLS enabled. Tables without an authenticated policy
-- remain server-only even if somebody accidentally grants schema visibility.
alter table public.accounts enable row level security;
alter table public.account_users enable row level security;
alter table public.operators enable row level security;
alter table public.merchant_config enable row level security;
alter table public.sales enable row level security;
alter table public.staff_pins enable row level security;
alter table public.pairings enable row level security;
alter table public.pair_attempts enable row level security;
alter table public.menus enable row level security;
alter table public.orders enable row level security;
alter table public.channel_links enable row level security;
alter table public.catalogs enable row level security;
alter table public.store_docs enable row level security;
alter table public.clients enable row level security;
alter table public.config_audit enable row level security;
alter table public.sale_audit enable row level security;
alter table public.account_audit enable row level security;
alter table public.reset_tokens enable row level security;
alter table public.table_sessions enable row level security;
alter table public.order_desk enable row level security;
alter table public.import_runs enable row level security;

create policy account_users_select_own
  on public.account_users for select to authenticated
  using (auth_user_id = auth.uid());

create policy merchant_config_select_own
  on public.merchant_config for select to authenticated
  using (private.owns_account(account_id));

create policy sales_select_own
  on public.sales for select to authenticated
  using (private.owns_merchant(merchant));
create policy sales_insert_own
  on public.sales for insert to authenticated
  with check (private.owns_merchant(merchant));
create policy sales_update_own
  on public.sales for update to authenticated
  using (private.owns_merchant(merchant))
  with check (private.owns_merchant(merchant));

create policy staff_pins_select_own
  on public.staff_pins for select to authenticated
  using (private.owns_merchant(merchant));

create policy pairings_select_own
  on public.pairings for select to authenticated
  using (private.owns_merchant(merchant));

-- Published menus are the only table intentionally readable anonymously.
create policy menus_public_read
  on public.menus for select to anon, authenticated
  using (true);
create policy menus_insert_own
  on public.menus for insert to authenticated
  with check (private.owns_merchant(merchant));
create policy menus_update_own
  on public.menus for update to authenticated
  using (private.owns_merchant(merchant))
  with check (private.owns_merchant(merchant));

create policy orders_select_own
  on public.orders for select to authenticated
  using (private.owns_merchant(merchant));
create policy orders_insert_own
  on public.orders for insert to authenticated
  with check (private.owns_merchant(merchant));
create policy orders_update_own
  on public.orders for update to authenticated
  using (private.owns_merchant(merchant))
  with check (private.owns_merchant(merchant));

create policy catalogs_select_own
  on public.catalogs for select to authenticated
  using (private.owns_merchant(merchant));
create policy catalogs_insert_own
  on public.catalogs for insert to authenticated
  with check (private.owns_merchant(merchant));
create policy catalogs_update_own
  on public.catalogs for update to authenticated
  using (private.owns_merchant(merchant))
  with check (private.owns_merchant(merchant));

create policy store_docs_select_own
  on public.store_docs for select to authenticated
  using (private.owns_merchant(merchant));
create policy store_docs_insert_own
  on public.store_docs for insert to authenticated
  with check (private.owns_merchant(merchant));
create policy store_docs_update_own
  on public.store_docs for update to authenticated
  using (private.owns_merchant(merchant))
  with check (private.owns_merchant(merchant));

create policy clients_select_own
  on public.clients for select to authenticated
  using (private.owns_merchant(merchant));
create policy clients_insert_own
  on public.clients for insert to authenticated
  with check (private.owns_merchant(merchant));
create policy clients_update_own
  on public.clients for update to authenticated
  using (private.owns_merchant(merchant))
  with check (private.owns_merchant(merchant));

create policy table_sessions_select_own
  on public.table_sessions for select to authenticated
  using (private.owns_merchant(merchant));
create policy table_sessions_update_own
  on public.table_sessions for update to authenticated
  using (private.owns_merchant(merchant))
  with check (private.owns_merchant(merchant));

create policy order_desk_select_own
  on public.order_desk for select to authenticated
  using (private.owns_merchant(merchant));

-- New tables are private until migrations grant the minimum required access.
revoke all on all tables in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;

grant select on public.menus to anon;
grant select on public.account_users, public.merchant_config,
  public.staff_pins, public.pairings, public.order_desk to authenticated;
grant select, insert, update on public.sales, public.menus, public.orders,
  public.catalogs, public.store_docs, public.clients, public.table_sessions
  to authenticated;

grant all on all tables in schema public to service_role;
grant usage, select on all sequences in schema public to service_role;

alter default privileges for role postgres in schema public
  revoke all on tables from anon, authenticated;
alter default privileges for role postgres in schema public
  revoke all on sequences from anon, authenticated;
alter default privileges for role postgres in schema public
  grant all on tables to service_role;
alter default privileges for role postgres in schema public
  grant usage, select on sequences to service_role;
alter default privileges for role postgres in schema public
  revoke execute on functions from public, anon, authenticated;
alter default privileges for role postgres in schema public
  grant execute on functions to service_role;

commit;
